# Generated by Django 2.2.16 on 2022-04-01 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='title_id',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title_id',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='titlegenre',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='titlegenre',
            old_name='title_id',
            new_name='title',
        ),
    ]
