# Generated by Django 2.2.16 on 2022-04-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220331_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title_id',
        ),
    ]
