# Generated by Django 2.2.16 on 2022-04-10 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220410_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(auto_created=True, default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
